ARG VARIANT="3"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# Install Node.js
ARG INSTALL_NODE="true"
ARG NODE_VERSION="lts/*"
RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
RUN apt-get update
RUN apt-get install -y gcc gfortran musl-dev
ENV PYTHONUNBUFFERED 1

# ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
# RUN /install.sh

# uv needs access to tmp, so we need to make it writable
# RUN chmod 777 /tmp