# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: dev
  outputs:
    dev:
      type: duckdb
      threads: 4
      external_root: "{{ env_var('MELTANO_PROJECT_ROOT') }}/data/data_catalog/analysis"
      path: ../data/data_catalog/mdsbox.duckdb
    staging:
      type: duckdb
      threads: 4
      external_root: /tmp/data_catalog/conformed
    prod:
      type: duckdb
      threads: 4
      external_root: /tmp/data_catalog/conformed
